import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import { Providers } from "./provider";
import Navbar from './components/navbar';
import MobNavbar from './components/mobNavbar';
import Footer from './components/footer';
import dynamic from 'next/dynamic';
// const inter = Inter({ subsets: ['latin'] })

const DynamicHeader = dynamic(() => import('./components/mobNavbar'), {
  ssr: false,
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body >
      
      <Providers>
      <Navbar/>
        {/* <MobNavbar/> */}
        <DynamicHeader/>
        {children}
        <Footer/>
        </Providers>
        <script src="https://upload-widget.cloudinary.com/global/all.js" type="text/javascript">  
</script>
        </body>
    </html>
  )
}
